[profile.default]
out = 'out'
libs = ['lib']
ffi = true
remappings = [
    "forge-std/=lib/forge-std/src/",
    "foundry-huff-neo/=lib/foundry-huff-neo/src/",
    "solmate/=lib/solmate/src/"
]

[profile.default.fuzz]
runs = 1000